### PR TITLE
add indication or remote, and meetings

### PR DESCRIPTION
**Pull request by shawna-slh**
1. Added Meetings to the title
2. Updated the summary
3. added " (in-person, remote)" or " (in-person)" to each point
4. Updated [For More Info](https://deploy-preview-69--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#for-more-information-speakers--organizers) section with link to [Accessibility of Remote Meetings](https://www.w3.org/TR/remote-meetings/) and Accessible Virtual Conferences

### CODE REVIEW

**Comment by shawna-slh** [comment]
Approved for publication under EOWG's https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Process_for_Minor_Changes by @bakkenb , @kakinney , and Shawn. Listed for EOWG review in [Work for this Week Review section](https://www.w3.org/WAI/EO/wiki/EOWG_Meetings#Minor_Changes_for_Review) and in 22 July meeting agenda.

**Comment by MicheleAWilliams-A11y** [comment]
Hi @shawna-slh, just a few notes:

**Arrange for good Internet connection when needed (in-person)**
At first this seems to apply to “remote” as well because speakers should have good internet connections for presenting. But the paragraph doesn’t lend itself to that so I suppose leave as-is (just noting on first glance it seemed to apply).

**Use a microphone {#usemic} (in-person)**
I think this applies to both because we want remote speakers to use microphones as well (built-in computer mics often have issues).

**Comment by shawna-slh** [comment]
Hi @MicheleAWilliams-A11y 

Reading through it, I strongly support your point from 22 July EOWG meeting that while some of the headings clearly apply to in-person and remote, the explanatory text is in-person focused and some doesn't apply well to remote.

A few things:
1. I edited the summary to make that more clear:
> This page helps you make your presentations, meetings, conferences, and training more accessible to everyone, particularly people with disabilities. **It focuses on in-person events and indicates overlapping issues with remote and hybrid events.**

2. You said:
>Use a microphone {#usemic} (in-person)
I think this applies to both because we want remote speakers to use microphones as well (built-in computer mics often have issues).

This is an example of an explanation for in-person that doesn't apply to remote:
> Some people might need the audio electronically, even in a small room. This includes people using [ALDs](https://deploy-preview-76--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#ald) and remote [captioners](https://deploy-preview-76--wai-presentations2all.netlify.app/teach-advocate/accessible-presentations/#captions). Note that if you ask “Can everyone hear me OK?” some people might be uncomfortable saying that they cannot.

For the issue of remote folks using a good microphone, perhaps that's better addressed related to setup, e.g.:
> Ensure adequate sound system, and arrange for microphones

-- but it needs work to cover remote well.

I'd like to save this one for the more robust remote update, if that's OK with you?

3. I'm imagining expanding this to better cover remote... and thinking about under several we would have some different info for in-person or remote.... and thinking that adds clutter... and thinking that we really need filters so people can choose in-person, remote, hybrid! I'll add an issue for that.

**Comment by MicheleAWilliams-A11y** [comment]
Hey there, here's a few responses:

1. Yes, I like that update and would give some cover for this interim state.
2. Funny, I was going to flag "Ensure adequate sound system, and arrange for microphones" but then when I saw "Use a microphone" I flagged that one instead. But agree that maybe we just pause on those in general.
3. The filters will be key indeed. Let me know if I can help. Not that I have an _abundance_ of time but I can certainly jump in a bit. I wrote the virtual meeting guide for SIGACCESS that you linked (thanks much - so exciting!) and I'm even currently consulting with a client for their hybrid conference, so these things are pretty fresh off the top of my head (that is, aren't a heavy lift to write out). I also would really love to send people to WAI so can't wait for this to officially be a thing!

**Comment by shawna-slh** [comment]
> I also would really love to send people to WAI so can't wait for this to officially be a thing!

@MicheleAWilliams-A11y  It's officially been published for a while: [How to Make Your Presentations and Meetings Accessible to All](https://www.w3.org/WAI/teach-advocate/accessible-presentations/)

I'm creating new issues for more updates...

**Comment by MicheleAWilliams-A11y** [comment]
Thanks, I meant when it's updated for remote (which is the focus of most of my peeps). I've known about the resource but it doesn't always apply. 

Regarding giving input, let's connect on how you would like to coordinate on that (e.g., is this part of other EO work with other members, should I just start writing and putting issues in GitHub, etc.)? Happy to pop over to email for that.

**Pull request merged**
